name: CI pipeline
# This workflow is triggered on pushes to the repository.
on:
  push:
  workflow_call:

jobs:
  lint:
    name: Go Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: '1.23.3'
          cache: false
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: v1.61.0
          args: --skip-files .*_test.go
  build:
    name: Test & Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: "1.23.3"
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
      - name: Run tests
        run: go test -race -coverpkg=./... ./... -coverprofile cover.out.tmp -covermode=atomic
      - name: Removes mocks from tests
        run: cat cover.out.tmp | grep -v "_mock.go" > cover.out
      - uses: codecov/codecov-action@v4
        with:
          file: ./cover.out
          token: ${{ secrets.CODECOV_TOKEN }}
